### ISSUE TITLE
Tabulated values should show all decimal values and use fixed width

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#14]
For things like stacking of pricing and historical pricing, you want to easily compare numbers.  Each column should have the same forced number of decimals and be fixed width characters so it stacks nicely.

**Comment by tylerjohneddy** [comment]
@BKdilse they have a fixed decimal, maybe make the values right justified so the decimal point is always lined up ?

**Comment by BKdilse** [comment]
@tylerjohneddy agreed, assigned to me.

**Comment by BKdilse** [comment]
Justification to right complete.  Hows it look @bennytehcat ?

**Comment by BKdilse** [comment]
this may need re-work, when we have large amounts.

**Comment by BKdilse** [comment]
Justification fixed, current massive orders will always screw this up.
