### ISSUE TITLE
Timestamp needs decimal places rounded up

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/Exchange#22]
If you have a look at order history, here is an example of how it's showing up:

`2021-04-09 11:14:41.416`

**Comment by tylerjohneddy** [comment]
How do you want it ?

**Comment by BKdilse** [comment]
`2021-04-09 11:14:41` ?

**Comment by tylerjohneddy** [comment]
${order.completedAt}

to

${#dates.format(order.completedAt, 'dd-MM-yyyy HH:mm:ss')}

example change to trade template to allow timestamp formatting
