### ISSUE TITLE
Decimals Issue with trades, using new script

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/Exchange#25]
e.g.

Price: (XMR) `0.000001`
Amount (GNTL) `100`
Amount XMR shows up as `0.00009999999999999999`

**Comment by BKdilse** [comment]
This looks to be a display only issue, as the trade on the backend is showing correct decimals.

**Comment by tylerjohneddy** [comment]
did this get fixed @BKdilse ?

**Comment by BKdilse** [comment]
fixed
