### ISSUE TITLE
Set all wallets to pre-created ones - New User gets an Error when accessing the Trades page

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/Exchange#27]
This is due to no wallets existing for the User.

Suggestion: Direct the User to the Wallets page on 1st login?

**Comment by tylerjohneddy** [comment]
i could make the code give an empty wallet if they havent created a wallet yet. should stop the error and user will beable to view the trades with out needing a wallet they might not use

**Comment by tylerjohneddy** [comment]
this turned out to casues more issues than is solved so rethinking that idea

**Comment by tylerjohneddy** [comment]
@BKdilse maybe we just create all wallets for the user, I guess it's not much overhead for us

**Comment by BKdilse** [comment]
@tylerjohneddy yes, let's just do that, as it also takes away the additional step for the user.

**Comment by tylerjohneddy** [comment]
change made, close if happy @BKdilse

**Comment by BKdilse** [comment]
confirmed working
