### ISSUE TITLE
[Documentation] Typos in Terms and Conditions 

### ISSUE THREAD

**Issue by adder-gntl** [The-GNTL-Project/Exchange#28]
Typos in the Terms and Conditions highlighted in bold italics below - 

Under _Changes to Terms and Conditions_:
- The GNTL Exchange may modify these Terms and Conditions by updating the "Last Updated" date at the top of these _**Termsa**_ and Conditions.
- By having already clicked on _**the the**_ "I Agree" button or checkbox, and by continuing to access or use our Services, you confirm your agreement to the modifications.

Under _Your Account_:
- You must maintain a strong password _**needs a period**_
- You _**authorise**_ The GNTL Exchange, to accept all instructions by anyone who has access to your account, regardless of whether they are _**authorised**_ or not. _(debatable here, I know it's UK vs US spelling (with an **S** vs a **Z**)_

Under _The GNTL Exchange_:
- A Coin may be suspended, without any notice, if we detect an issue with any part of the technology. We accept no _**liablility**_ for any loss incurred.

Under _Running of your account_: _(**your** and **account** should be capitalized to keep with the rest of the document)_
- You should regularly withdraw balances, to avoid any loss due to technology failures, as _**these balance**_ could get lost. **_(should be plural)_**
- You will be responsible for paying all fees charged by the coin network, as _**welll**_ GNTL Exchange fees **_(also add period here)_**
- You may not use a bot service **_(add period here)_**

**Comment by BKdilse** [comment]
All corrected.
