### ISSUE TITLE
[Interface/Enhancement] Notification of insufficient balance

### ISSUE THREAD

**Issue by adder-gntl** [The-GNTL-Project/Exchange#29]
When trying to buy or sell with amounts over your current balance, transaction is not processed but it doesn't give any notification or error message. An "Insufficient balance" message should be added to let users know there was an issue.

**Comment by tylerjohneddy** [comment]
please test and close if happy

**Comment by tylerjohneddy** [comment]
This should be in the next update, get a nice big yellow banner to say youve not got enough

**Comment by adder-gntl** [comment]
Looks good, I've tested this now and works a champ.
