### ISSUE TITLE
[Bug] Completed At should be date/time, showing true/false

### ISSUE THREAD

**Issue by adder-gntl** [The-GNTL-Project/Exchange#31]
On trades screen in either My Orders or My Trades, the **Completed At** field is showing true or false. This should be date/time.

![image](https://user-images.githubusercontent.com/82879172/115893286-9eca5880-a41d-11eb-9c96-c9adfd926f46.png)

**Comment by adder-gntl** [comment]
It appears that **true** entries are the **buy** orders, **false** entries are **sell** orders

**Comment by tylerjohneddy** [comment]
linked to #38

**Comment by BKdilse** [comment]
Dates re-instated.  @tylerjohneddy Is this going to be filtered on the backend or frontend?

**Comment by BKdilse** [comment]
fixed in latest release, and now live.
