### ISSUE TITLE
Emails to come from gntl domain

### ISSUE THREAD

**Issue by tylerjohneddy** [The-GNTL-Project/Exchange#32]
Currently the exchange uses a temporary Gmail email, this should be moved so it comes from a gntl domain from something like smtp2go

**Comment by bennytehcat** [comment]
What would you like as the sender? I can setup an alias. I'm using nullmailer to run it locally. 

exchange@gntl.cash seems appropriate.

**Comment by BKdilse** [comment]
Good point, that domain is better for this.  What you've suggested sounds good @bennytehcat

**Comment by BKdilse** [comment]
gntlproject@gmail.com is now being used, but we need the alias changed at some point.

**Comment by tylerjohneddy** [comment]
could i also have the login details to try and fix this please
@BKdilse

**Comment by tylerjohneddy** [comment]
this has been tested and works. it will be in the next release

**Comment by BKdilse** [comment]
Can confirm this is now live, and works.
