### ISSUE TITLE
Should we allow full access to the order book to see at what height your order is at?

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#33]
Would it be beneficial to show the actual order book? That's bugging me a bit about some trading sites, not really knowing where in the ledger you stand for a bid/ask price.  For instance, if there is 10000 on order, and I am only 50  of that 10000, I'd like to know when my 50 will be executed, or where I stand in that stack of 10000

**Comment by tylerjohneddy** [comment]
@BKdilse any ideas on how best to show this? @bennytehcat is there any trading platforms that you could show us how they have done it?
