### ISSUE TITLE
Selecting one of the buy or sell orders (bottom left) should pre fill your proposed order to save typing in the buy/sell price

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#36]

**Comment by BKdilse** [comment]
Script created, work in progress,, with the following limitations which will be addressed:

1. Currently it only grabs the 1st row.
2. Does not update the trade (fees).

**Comment by BKdilse** [comment]
Now grabs any row you click on.  Thanks @tylerjohneddy
