### ISSUE TITLE
My orders should clear once the trade is done

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#38]
i would have thought but it doesn't, it should move to my trades then

**Comment by tylerjohneddy** [comment]
#41 is a symptom of this issue

**Comment by BKdilse** [comment]
Dates re-instated. @tylerjohneddy Is this going to be filtered on the backend or frontend?

**Comment by baldtrooper** [comment]
Dates work but GNTL is still 0 and this bug still happens my orders and my trades are the same

**Comment by BKdilse** [comment]
This is now implemented.
