### ISSUE TITLE
Second login search in my trades is now blank should this keep my history

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#39]

**Comment by baldtrooper** [comment]
Basically on my second time testing i went to the trading screen and on the right second under my trades i was expecting to see my previous trades but it was blank. interestingly whe i did then trade they appeared?

**Comment by tylerjohneddy** [comment]
@baldtrooper is this repeatable ?

**Comment by baldtrooper** [comment]
Just logged in again and i can see my 2 previous trades, so i guess its resolved? i'll close it and re-open if i notice it again
