### ISSUE TITLE
Missing some error traping when not putting a value in the price XMR box (sell)

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#40]
Got a white screen of death saying this:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Apr 26 17:24:22 UTC 2021
There was an unexpected error (type=Bad Request, status=400).

**Comment by BKdilse** [comment]
@baldtrooper shouldd not be fixed, are you able to confirm and close please?

**Comment by baldtrooper** [comment]
Resolved

**Comment by BKdilse** [comment]
Had to revert input type from number, back to text, as its causing further issues.

**Comment by BKdilse** [comment]
Now fixed again
