### ISSUE TITLE
In my trades the amount 'GNTL' shows 0 

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#41]
Previous trades don't show an amount under GNTL, all are 0.00000000

**Comment by tylerjohneddy** [comment]
this is caused because the trade has completed. when we fix #38 this should fix this issue

**Comment by tylerjohneddy** [comment]
@BKdilse can you have a look at the information that is being displayed, if we are showing everything we want then might need to look deeper into why its showing 0's

**Comment by BKdilse** [comment]
@tylerjohneddy I need the endpoint from the backend for this.

**Comment by BKdilse** [comment]
fixed.
