### ISSUE TITLE
CSS Color Scheme Red/Green Adjustments

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#47]
The buy and sell buttons are harsh tones of green/red.  I suggest changing it to:

Red Sell Button: `#cc0000 (204,0,0)`
Green Buy Button: `#009900 (0,153,0)`
Active Buy Table:` #66cc66 (102,204,102)`
Active Sell Table: (Leave as-is)

The active buy table is a bit too light for the white text, that other shade of green should help the white pop a bit more, if not, try #669966 (102,153,102). Red/Green Sell/Buy buttons are a bit toned down from the pure color.

**Comment by BKdilse** [comment]
Changed.  I went with #669966 for te Active table, as the other one was not right.  The whole Black/White theme is only following our other sites, but we can change it at some point.
