### ISSUE TITLE
How many exchange pairs should we host?

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#50]
In order for GNTL to have a value, it must be linked to another coin, giving it value.  The question is if we should limit offerings, for instance, only GNTL-XMR.  Or if GNTL should be the basis of our market, and we link to multiple coins: GNTL-ARQ, GNTL-XHV, etc.

**Comment by BKdilse** [comment]
GNTL will be the primary base.
Monero will be the secondary base.
We will have pretty much all the coins from our Mining Pools listed as pairs for both coins.
