### ISSUE TITLE
Do we seed the initial order books for each exchange pair

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#51]
This issue is linked to Issue #50.  

If we open a new exchange, the order books are empty until people start using the exchange.  If we populate the order books with dev-funding we can help to steer the price of GNTL.  This would need to be coordinated well with real-time market values at the time of going live.  It makes Issue #50 perhaps be something that is implemented slowly (few pairings to multiple).

**Comment by BKdilse** [comment]
Initial orders would have to be created by the core team.

**Comment by BKdilse** [comment]
This will be based on tipbot-trading as a starting point.

**Comment by BKdilse** [comment]
As we now have tipbot and Exbitron, we will be basing prices accordingly.
