### ISSUE TITLE
Add "Register" link separate from login

### ISSUE THREAD

**Issue by nabeards** [The-GNTL-Project/Exchange#59]
It should be more obvious how to register from the home page.

**Comment by BKdilse** [comment]
We already have a Login button, so not sure why we would need a separate Register button.  Happy to add it in, but maybe needs a discussion/votes?

**Comment by nabeards** [comment]
I had no idea what to do when I got to the landing page.

**Comment by BKdilse** [comment]
this has been added as a separate icon now.
