### ISSUE TITLE
Clicking on an order lower in the list should add up all other orders above

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/Exchange#65]
Is this something we want?

**Comment by bennytehcat** [comment]
So the options would be:

A) Clicking an existing order in the book duplicates the order

B) Sweep of every price above the price you select in terms of qty, but at the price you selected

If so, you (A) is a limit, (B) is a market order.  We do want the ability to place market orders, but that should not preclude (A).  Meaning, perhaps we need a toggle button in the bid/ask table to select market/limit.  Limit would look like it does now, Market would eliminate the price box, and make it a qty and total amount field.

Am I understanding this correctly?

**Comment by BKdilse** [comment]
Maybe.  Basically, we are talking about the same functionality TO offers.  No extra buttons, click and fill 1 order, or multiple ones at the prices they are set at.

**Comment by tylerjohneddy** [comment]
@bennytehcat option (B) has been implemented, dont think option (A) is something we want. but can reopen this issue if there is enough demand
