### ISSUE TITLE
pairs.html doesn't render the pairs list properly

### ISSUE THREAD

**Issue by XiovV** [The-GNTL-Project/Exchange#67]
![image](https://user-images.githubusercontent.com/20326947/119135639-fa006280-ba3e-11eb-8f26-4775419a7bdd.png)

Also, when I click on a pair I get this error:
![image](https://user-images.githubusercontent.com/20326947/119135724-16040400-ba3f-11eb-9b63-dd8e60582758.png)

I looked through the existing issues and I couldn't find any related to this, so I'm sorry if I missed some Issue that mentioned these problems.

**Comment by tylerjohneddy** [comment]
#68

**Comment by tylerjohneddy** [comment]
@XiovV  the error is probably because you have no wallets, create the wallets and you should be golden

**Comment by BKdilse** [comment]
@XiovV this is now fixed.
