### ISSUE TITLE
create users wallets automatically 

### ISSUE THREAD

**Issue by tylerjohneddy** [The-GNTL-Project/Exchange#68]
currently the user has to manually create the wallets, this causes problems when trying to access the trade pages.

**Comment by tylerjohneddy** [comment]
#67

**Comment by tylerjohneddy** [comment]
added in latest push, please test and close, if RPC is not running wallet creation will still fail

**Comment by tylerjohneddy** [comment]
#27 duplicate

**Comment by BKdilse** [comment]
confirmed change is in place.
