### ISSUE TITLE
Add a conversion ticker to bottom of trading window for XMR-BTC-USD-GBP

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Exchange#71]
Trading in XMR is weird.  Let's put something up to bring the numbers back to something more familiar.

**Comment by tylerjohneddy** [comment]
You'll be trading in GNTL, so this will be really interesting

**Comment by BKdilse** [comment]
Added Temporary pricing at the top of the trades page for now, to give some idea.  Can move it around/adjust.  How is that for starters @bennytehcat ?

**Comment by bennytehcat** [comment]
Exactly what I was saying, something basic, how's this for layout:

![Capture](https://user-images.githubusercontent.com/49038226/119200957-f929f980-ba5b-11eb-8004-6db0727a8059.PNG)

**Comment by BKdilse** [comment]
Got it improved now, all at the top.

**Comment by tylerjohneddy** [comment]
can this be closed?

**Comment by BKdilse** [comment]
Pricing available at the top of page.
