### ISSUE TITLE
Fees being charged on orders rather than transactions

### ISSUE THREAD

**Issue by ElectricDosh** [The-GNTL-Project/Exchange#74]
Fees should be charged on the value of completed transactions at time of execution, not on the order value at the time the order is placed. Charging a full fee on a partially fulfilled order disincentivizes placing any order that risks not being completely filled, and imo will be highly off-putting to big money and small high-frequency traders alike.

**Comment by ElectricDosh** [comment]
My suggestion, if possible, would be to have a discount on fees for makers vs takers, so as to incentivize filling the order books.

**Comment by tylerjohneddy** [comment]
Once the update is live, please test and if happy close

**Comment by ElectricDosh** [comment]
Unsure if #77 is related, will leave open for now.

**Comment by BKdilse** [comment]
@ElectricDosh are you able to test this one out?

**Comment by ElectricDosh** [comment]
Yeah this looks good now, although the fee isn't included in the transaction history, is that right?

**Comment by BKdilse** [comment]
Would it be better to show the fee per trade in the history @tylerjohneddy ?

**Comment by BKdilse** [comment]
Tested successfully, Fees not being displayed is a separate issue.
